apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-credentials
  namespace: default
spec:
  encryptedData:
    connection: AgBXK6Ti4WQW6ODnVpflLIWgM1Ln8oX78dQqM85pda9nLwjk/MZkDn4c5YnxzTl/6i+UdBrgFx16sbgNw3cyEtEO57MVez7E
+w3oTMsbdq/7ki+huOd2tg7bXBZtGFdZCm9i38Ct+PxbtWCA9//GLrqRUotAffigjxFLSMVo962uM71bwkgL4z7vTy7/No560MVchKjd3fpgnSo2
8R0Jao+AX742uvQ9gtjM65c/1CrwWILofjrzg1/PBcgUhx9gE1rhDNg+EAs8INwi+y1smLrLVAX+OJxSR2VsVZ0RsWT3sVs60a32BRKdvee7NpO9
3AQxs8d0h5XbOqw/gSAiKa8sF9v8MuxXo6XmuPwTcDQG774mHF0K2q6fYSo3GflXpm8OpxfQnL25AhgSanm0JqBPhOv5a4VIIzyDK/k8aIUeAQJ/
56cLdXghL9ZFudUD09byUD4Td8KorW4pyVZjYlCCkf83utf8pT9g15QHnFxBGGYEdO2fKvUZf9657Kf0yiKPs4iqQdWlGnx2sq0hLjDyRYGKZKB2
TM2AVZXGZPLAr967lrR+wzduIwe+0HPNlSYbw/7hs0/hYsLMhu+HQ8cf/AMIiuBQT0erEr7H8rM5sR6kENq8ANJPmhu1+fbXZclq5AHOsxKTJLBn
ZQegafZ0K6g2gNh6QczeH5Ywl70LUnuphT6aL/uBEZbI2JEzmAmMPlNW7jF4NuPIt5CurnlFI6HPuzjPsUP6nLydh3IiXVM=
    password: AgB8zzn0vCohJRNjwAgXAdS+/33K3c/wEbmZ9q8/eskciEUzdVvUVcg6Fti4uRTpmbS5Q+RJ32FReV+wVXiodsRTuV+fhMW6fJ
q/kpgYnMhJbMIOgrZYe4qiKXXm9RoWFgtxboJ/9nSHrHrHaDOHTVjZTVxJlvrhX86AN3vnjXcpxebUqlwoaWuaFH0T/JCb1Wx6LdFgaBTWMuXMBd
D1Es0OrZl2/VzILKC/H3NuqSIz9PERX6/tPSt9uFGIzMJIO396N7i1+jw8UbhQqSH7KwlztfEuO8ITVxrktMx0Fu3UohawgH9efeEUXIRWp/E/og
DzVWEIfqOPtB1Ce0MF8Lst4/1TOyWJ/QsKwwxWKJYxNOAvGF6Zjkhi59UX6X4NtOFNemzAcqEjhStyG5n69vOy66fKdQFUuxSqPEMr+1RDpWCBy7
CQH1ZLq6eBxh8FgjmVrzbhIP1Y+8H7uAE+WLHxPahmnyd5Sg+MIe1ZpaSNkROpmY9VvRtW8v+mz2EyYyRbgVQ1VYv10ihjOpWKNLEB2d+/mSETXW
+qm0qN93UahDWRV76kxK9D6Y2MIBeJ3fldCmxH0TFa7hdn+JK61irUyvFvopL9B9dRcZUdi5OfrQ8iWJYkA50uWXX57Rm/J9T7m9ZdIaCIE3inaX
TuaF2dxkQTsVUz22BC5x+C713Fv7320vec2+EmmVBJS7WRK+pY7gTCsO9mqYg2Rh/lid8=
    username: AgBiMwj8evsesLyq+mGLgFbcymDHD9/6zzD0AyexcAU28DSYEqJPDG6pM1Md7lqIJWOsuJYROhL3YzZQDlmJTsH3LGUfulWFNc
GRGPXmm0r0O6wIOUWl7et/otYgsgnuwJem5y47YP2TkYdPITBvX4n23hZ2o182ipANfMAcO7IIV3msZybAAnkaF/rbVIGkY6yShE/DbuOceOjM6g
G2gZyj+s92ORofM0z0nTweG/YMKyq8IlEB1tyaPLMs7qFU9Zjq2tevRMgzx5/ucuOVbm9m6CCYbQW+QYIjd0py5jBT6bWWuFcw548oOdxiLlZzYC
AjEuEIPb5UnRP49vVP8BYb1SjDoNRkaIB1K0yFKLDkVukxvL4qKlnmLzhX2vPx4kAATMZIWWW3QaNDgco/pTfbjnZ/0+9ih3RGt3ZMoFo6v3lu56
J+D1niz1AvzyZ+3UHtykqKoFYFKoKf8lcHVzKrGaAWjemuIP4nE3Qoj/ikv+0/XLzaJqURH8aBrSzToTACQ6Z3qSv8vYp0UYjXK5qAVul7cj3fDV
liEXKlvarpPlfQQ+atqmGQhBfTfLqvrYJ1itIwc+C4sqfVVqkkO8/ahEJEVnKfuESjDGluSLWRj8yBuOtTa1Ys+oKDUccaOboO+Vzshz5tOOjNQS
oCbmtJKKk3YRCPbADfD/kb+p42oaZwCiaeVRbhzXfDxJMclldY2FVNOrZpqY0FGg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysql-credentials
      namespace: default
    type: Opaque

